# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainauthorization',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainauthorization',
            name='validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
