# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20160202_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainauthorization',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('pending', 'pending'), ('processing', 'processing'), ('valid', 'valid'), ('invalid', 'invalid'), ('revoked', 'revoked')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='domainauthorization',
            name='token',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
