# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import domains.models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20160203_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainauthorization',
            name='token',
            field=models.CharField(default=domains.models.generate_domain_token, editable=False, max_length=255),
        ),
    ]
