# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import push.models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_auto_20160211_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushapplication',
            name='jws_key_status',
            field=models.CharField(choices=[('pending', 'pending'), ('valid', 'valid'), ('invalid', 'invalid')], default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='pushapplication',
            name='jws_key_token',
            field=models.CharField(default=push.models.generate_jws_key_token, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='pushapplication',
            name='validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
