# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_auto_20160218_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushapplication',
            old_name='jws_key_status',
            new_name='vapid_key_status',
        ),
        migrations.RenameField(
            model_name='pushapplication',
            old_name='jws_key_token',
            new_name='vapid_key_token',
        ),
        migrations.RemoveField(
            model_name='pushapplication',
            name='jws_key',
        ),
        migrations.AddField(
            model_name='pushapplication',
            name='vapid_key',
            field=models.CharField(blank=True, help_text='VAPID p256ecdsa value; url-safe base-64 encoded.', max_length=255),
        ),
    ]
