# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0004_auto_20160218_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushapplication',
            name='vapid_key_status',
            field=models.CharField(choices=[('pending', 'pending'), ('valid', 'valid'), ('invalid', 'invalid'), ('recording', 'recording')], default='pending', max_length=255),
        ),
    ]
