# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0005_auto_20160229_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushapplication',
            name='vapid_key',
            field=models.CharField(help_text='VAPID p256ecdsa value; url-safe base-64 encoded.', max_length=255),
        ),
    ]
